import { AccordionUi, T, AccordionItemType } from "@mantle/ui";
import Link from "next/link";

const faqList: Array<AccordionItemType> = [
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        What is LSP?
      </T>
    ),
    content: (
      <T variant="microBody14">
        Mantle LSP is a permissionless ETH liquid staking protocol deployed on
        Ethereum L1 and is governed by{" "}
        <Link
          href="https://docs.mantle.xyz/governance"
          target="_blank"
          className="underline"
        >
          Mantle Governance
        </Link>
        .
      </T>
    ),
    value: "faq-1",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        What roles does mETH play?
      </T>
    ),
    content: (
      <T variant="microBody14">
        mETH is the receipt token of Mantle LSP. It is a reward accumulating and
        permissionless ERC-20 token that can be used by various applications
        such as: DeFi applications on Ethereum L1, Mantle Network L2, and any
        other chains; and centralized applications such as exchanges.
      </T>
    ),
    value: "faq-2",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        How does LSP accrue value?
      </T>
    ),
    content: (
      <T variant="microBody14">
        The value of mETH is designed to increase over time as staking rewards
        are earned. While the staked ETH earns rewards, these rewards are
        automatically re-staked, and the value accrues directly to the mETH
        token.
      </T>
    ),
    value: "faq-3",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        How long until I receive my first reward when staking?
      </T>
    ),
    content: (
      <T variant="microBody14">
        The amount of your mETH tokens does not change. Instead, the price of
        mETH increases compared to ETH as the staking rewards are accrued. The
        value increase is visible every 8 hours, when oracles update the token
        rewards.
      </T>
    ),
    value: "faq-4",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        How long does unstaking take?
      </T>
    ),
    content: (
      <T variant="microBody14">
        Currently, the average unstaking time is about 3 days, depending on
        network conditions and protocol specifics. Once your funds are
        available, you will be able to claim them via the user interface on{" "}
        <Link
          href="https://lsp.mantle.xyz"
          target="_blank"
          className="underline"
        >
          https://lsp.mantle.xyz
        </Link>
      </T>
    ),
    value: "faq-5",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        What is the fee structure?
      </T>
    ),
    content: (
      <T variant="microBody14">
        A 10% fee is levied on the staking rewards by the LSP. This fee is then
        divided between the node maintainers and the governing body of the
        Mantle LSP. Consequently, users take home 90% of the staking gains
        generated by the network.
      </T>
    ),
    value: "faq-6",
  },
  {
    trigger: (
      <T className="text-type-primary" variant="microBody14">
        Where can I find more details?
      </T>
    ),
    content: (
      <T variant="microBody14">
        Please visit{" "}
        <Link
          href="https://docs.mantle.xyz/under-development-mantle-lsp/introduction/overview"
          target="_blank"
          className="underline"
        >
          this page
        </Link>{" "}
        for more details about LSP.
      </T>
    ),
    value: "faq-7",
  },
];

export function Faq() {
  return (
    <div className="flex gap-3">
      <AccordionUi list={faqList} className="flex flex-col w-full bg-black" />
    </div>
  );
}
